version: '3'
networks:  
  default: 
    name: ${AVENIRS_NETWORK}
    external: true             # Created via bootstrap script
      
include:
  # - ./services/openldap/docker-compose.yml
  # - ./services/apisix/apisix-docker/example/docker-compose.yml
  # - ./services/cas/cas-overlay-template/docker-compose.yml
  # - ./services/apache/docker-compose.yml
  # - ./services/kafka/docker-compose.yml
  # - ./services/node/docker-compose.yml
  # - ./services/avenirs-api/docker-compose.yml
  - ./services/postgresql/docker-compose.yml