version: '3'
networks: 
  default: 
    name: avenirs-network
    driver: bridge
include:
  - ./services/openldap/docker-compose.yml
  - ./services/apisix/apisix-docker/example/docker-compose.yml
  - ./services/cas/cas-overlay-template/docker-compose.yml

