networks:  
  default: 
    name: ${AVENIRS_NETWORK}
    external: true             # Created via bootstrap script
      
include:
  - path: ./services/postgresql/docker-compose.yml
    env_file:
      - .env
      - ./services/postgresql/.env

# This feature is temporarily disabled until you start using this service
#  - path: ./services/openldap/docker-compose.yml
#    env_file:
#      - .env
#      - ./services/openldap/.env

  - path: ./services/cas/cas-overlay-template/docker-compose.yml
    env_file:
      - .env
      - ./services/cas/cas-overlay-template/.env

  - path: ./services/apache/docker-compose.yml
    env_file:
      - .env
      - ./services/apache/.env

  - path: ./services/apisix/apisix-docker/example/docker-compose.yml
    env_file:
      - .env
      - ./services/apisix/apisix-docker/example/.env

# This feature is temporarily disabled until you start using this service
#  - path: ./services/kafka/docker-compose.yml
#    env_file:
#      - .env
#      - ./services/kafka/.env

# This feature is temporarily disabled until you start using this service
#  - path: ./services/node/docker-compose.yml
##    env_file:
##      - .env
##      - ./services/node/.env

  - path: ./services/avenirs-portfolio/docker-compose.yml
    env_file:
      - .env
      - ./services/avenirs-portfolio/.env

# This feature is temporarily disabled until you start using this service
#  - path: ./services/grafana/docker-compose.yml
#    env_file:
#      - .env
#      - ./services/grafana/.env

  - path: ./services/opensearch/docker-compose.yml
    env_file:
      - .env
      - ./services/opensearch/.env

# This feature is temporarily disabled until you start using this service
#  - path: ./services/prometheus/docker-compose.yml
#    env_file:
#      - .env
#      - ./services/prometheus/.env

  - path: ./services/valkey/docker-compose.yml
    env_file:
      - .env
      - ./services/valkey/.env