version: '3'
networks:  
  default: 
    name: avenirs-network
    external: true             # Created via bootstrap script
      
#    driver: bridge
include:
  - ./services/openldap/docker-compose.yml
  - ./services/apisix/apisix-docker/example/docker-compose.yml
  - ./services/cas/cas-overlay-template/docker-compose.yml
  - ./services/apache/docker-compose.yml
