# #! /bin/bash

#----------------------------------------#
# Bootstrap script for Avenirs portfolio #
#                                        #  
#----------------------------------------#

AVENIRS_PORTFOLIO_SCRIPT_DIR=`dirname $0`

# Initialization
. $AVENIRS_PORTFOLIO_SCRIPT_DIR/../../../scripts/srv-dev-commons.sh
init_commons $*
info "Avenirs portfolio bootstrapping started."

. $AVENIRS_PORTFOLIO_SCRIPT_DIR/avenirs-portfolio-env.sh $AVENIRS_PORTFOLIO_SCRIPT_DIR 2> /dev/null \
    || err "Unable to source $AVENIRS_PORTFOLIO_SCRIPT_DIR/avenirs-portfolio-env.sh"

# Initialization of the local branch of avenirs-portfolio-storage if needed.
cd $AVENIRS_PORTFOLIO_STORAGE_REPOSITORY_DIR || err "Unable to enter $AVENIRS_PORTFOLIO_STORAGE_REPOSITORY_DIR"
if [ -z "`git branch   | grep $AVENIRS_PORTFOLIO_STORAGE_LOCAL_BRANCH`" ]
then
    verbose "Switching to branch $AVENIRS_PORTFOLIO_STORAGE_REMOTE_BRANCH (local branch $AVENIRS_PORTFOLIO_STORAGE_LOCAL_BRANCH)"
    git checkout -B $AVENIRS_PORTFOLIO_STORAGE_LOCAL_BRANCH $AVENIRS_PORTFOLIO_STORAGE_REMOTE_BRANCH || err "unable to create branch $AVENIRS_PORTFOLIO_STORAGE_LOCAL_BRANCH from $AVENIRS_PORTFOLIO_STORAGE_REMOTE_BRANCH"
else 
    verbose "Local APISIX branch found $AVENIRS_PORTFOLIO_STORAGE_LOCAL_BRANCH"
fi
cd - >/dev/null


# .env file generation
echo "AVENIRS_NETWORK=$AVENIRS_NETWORK" > $AVENIRS_PORTFOLIO_ENV_FILE


# ---- avenirs-portfolio-storage

# git branches 
init_git_repository $AVENIRS_PORTFOLIO_STORAGE_REPOSITORY_DIR $AVENIRS_PORTFOLIO_STORAGE_REMOTE_BRANCH $AVENIRS_PORTFOLIO_STORAGE_LOCAL_BRANCH

# Network check
check_network

# Overlay files
echo "install_overlay $AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR $AVENIRS_PORTFOLIO_STORAGE_REPOSITORY_DIR"
install_overlay $AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR $AVENIRS_PORTFOLIO_STORAGE_REPOSITORY_DIR


# .env file generation
echo "AVENIRS_PORTFOLIO_STORAGE_CONTAINER_NAME=$AVENIRS_PORTFOLIO_STORAGE_CONTAINER_NAME" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_STORAGE_CONTAINER_PORT=$AVENIRS_PORTFOLIO_STORAGE_CONTAINER_PORT" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_STORAGE_VERSION=$AVENIRS_PORTFOLIO_STORAGE_VERSION" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR=$AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_STORAGE_OVERLAY_BASENAME=$AVENIRS_PORTFOLIO_STORAGE_OVERLAY_BASENAME" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_STORAGE_SPRING_ENV_FILE=$AVENIRS_PORTFOLIO_STORAGE_SPRING_ENV_FILE" >> $AVENIRS_PORTFOLIO_ENV_FILE

# Spring env properties
echo "spring.datasource.url=jdbc:postgresql://$AVENIRS_POSTGRESQL_PRIMARY_CONTAINER_NAME:5432/avenirs_access_control" > $AVENIRS_PORTFOLIO_STORAGE_SPRING_ENV_FILE;


# ---- avenirs-portfolio-security
init_git_repository $AVENIRS_PORTFOLIO_SECURITY_REPOSITORY_DIR $AVENIRS_PORTFOLIO_SECURITY_REMOTE_BRANCH $AVENIRS_PORTFOLIO_SECURITY_LOCAL_BRANCH

# Network check
check_network

# Overlay files
echo "install_overlay $AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR $AVENIRS_PORTFOLIO_SECURITY_REPOSITORY_DIR"
install_overlay $AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR $AVENIRS_PORTFOLIO_SECURITY_REPOSITORY_DIR


# .env file generation
echo "AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME=$AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT=$AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_SECURITY_VERSION=$AVENIRS_PORTFOLIO_SECURITY_VERSION" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR=$AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_SECURITY_OVERLAY_BASENAME=$AVENIRS_PORTFOLIO_SECURITY_OVERLAY_BASENAME" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_SECURITY_SPRING_ENV_FILE=$AVENIRS_PORTFOLIO_SECURITY_SPRING_ENV_FILE" >> $AVENIRS_PORTFOLIO_ENV_FILE
echo "AVENIRS_PORTFOLIO_SECURITY_OIDC_FILE=$AVENIRS_PORTFOLIO_SECURITY_OIDC_FILE" >> $AVENIRS_PORTFOLIO_ENV_FILE

# Spring env properties
clientId=`cat $AVENIRS_PORTFOLIO_SCRIPT_DIR/../../cas/avenirs-cas-overlay/etc/cas/services/oidc-callback.json  | grep clientId | cut -d ':' -f 2 | sed "s/\( *\"\,\? *\)//g"`
clientSecret=`cat $AVENIRS_PORTFOLIO_SCRIPT_DIR/../../cas/avenirs-cas-overlay/etc/cas/services/oidc-callback.json  | grep clientSecret | cut -d ':' -f 2 | sed "s/\( *\"\,\? *\)//g"`
#echo "spring.datasource.url=jdbc:postgresql://$AVENIRS_POSTGRESQL_PRIMARY_CONTAINER_NAME:5432/avenirs_access_control" > $AVENIRS_PORTFOLIO_SECURITY_SPRING_ENV_FILE;
echo -ne "{\nclientId:$clientId\nclientSecret:$clientSecret\n}\n">$AVENIRS_PORTFOLIO_SECURITY_OIDC_FILE;





info "Avenirs portfolio bootstrapping completed."

