# #! /bin/bash

#--------------------------------------#
# Bootstrap script for Debezium        #
#                                      #  
# Initialize the repository and copy   #
# the files from the overlay directory #
# to the repository                    #
#--------------------------------------#

# Initialization
 DEBEZIUM_SCRIPT_DIR=`dirname $0`
. $DEBEZIUM_SCRIPT_DIR/../../../scripts/srv-dev-commons.sh
init_help "`basename $0`" 
init_commons $*
info "Debezium bootstrapping started."
. $DEBEZIUM_SCRIPT_DIR/debezium-env.sh $DEBEZIUM_SCRIPT_DIR || err "Unable to source $PWD/$DEBEZIUM_SCRIPT_DIR/debezium-env.sh"


# Network check
check_network

# Générer le fichier .env pour Docker Compose
echo "Generating  $DEBEZIUM_ENV_FILE file for Debezium..."
cat > $DEBEZIUM_ENV_FILE << EOL
# Generated by script $0 do not edit 
# $(date)
AVENIRS_POSTGRESQL_PRIMARY_CONTAINER_NAME=${AVENIRS_POSTGRESQL_PRIMARY_CONTAINER_NAME}
AVENIRS_POSTGRESQL_SECONDARY1_CONTAINER_NAME=${AVENIRS_POSTGRESQL_SECONDARY1_CONTAINER_NAME}
AVENIRS_POSTGRESQL_SECONDARY2_CONTAINER_NAME=${AVENIRS_POSTGRESQL_SECONDARY2_CONTAINER_NAME}
AVENIRS_POSTGRESQL_SECONDARY_CDC_CONTAINER_NAME=${AVENIRS_POSTGRESQL_SECONDARY_CDC_CONTAINER_NAME}
AVENIRS_DEBEZIUM_CONTAINER_NAME=${AVENIRS_DEBEZIUM_CONTAINER_NAME}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
AVENIRS_KAFKA_CONTAINER_NAME=${AVENIRS_KAFKA_CONTAINER_NAME}
EOL
echo ".env file generated at $DEBEZIUM_ENV_FILE"


info "Debezium bootstrapping completed."