FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build-only
RUN npm run type-check
RUN npm run lint

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html/cofolio
COPY --from=build /app/.env /usr/share/nginx/html/cofolio/.env
RUN cat > /etc/nginx/conf.d/default.conf << 'EOL'
server {
    listen 80;
    server_name localhost;

    location /cofolio/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /cofolio/index.html;
    }
    
}
EOL
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]