

FROM eclipse-temurin:17-jdk-alpine as build
ARG OVERLAY_DIR
ENV AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR=$OVERLAY_DIR
WORKDIR /workspace/app
RUN echo "AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR $AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR"
COPY ./avenirs-portfolio-storage/mvnw .
COPY ./avenirs-portfolio-storage/.mvn .mvn
COPY ./avenirs-portfolio-storage/pom.xml .
COPY ./avenirs-portfolio-storage/src src
#COPY ${AVENIRS_PORTFOLIO_STORAGE_OVERLAY_DIR}/src/main/resources/env.properties.no-git src/main/resources/env.properties
COPY ${AVENIRS_PORTFOLIO_STORAGE_SPRING_ENV_FILE} src/main/resources/

RUN ./mvnw clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:17-jdk-alpine
WORKDIR /workspace/app
ARG AVENIRS_PORTFOLIO_STORAGE_VERSION=0.0.1
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-storage-${AVENIRS_PORTFOLIO_STORAGE_VERSION}-SNAPSHOT.jar /app/avenirs-portfolio-storage.jar

ENTRYPOINT ["java", "-server", "-noverify", "-Xmx2048M", "-jar", "/app/avenirs-portfolio-storage.jar"]