services:
  avenirs-portfolio-security:
    container_name: ${AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME}
   
    build:
      context: .
      dockerfile: ./Dockerfile-avenirs-portfolio-security
      args:
       AVENIRS_PORTFOLIO_SECURITY_VERSION: ${AVENIRS_PORTFOLIO_SECURITY_VERSION}
       OVERLAY_DIR: ${AVENIRS_PORTFOLIO_SECURITY_OVERLAY_BASENAME}
    restart: always
    ports:
      - "${AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT}:12000"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    depends_on:
      - postgresql-primary
    networks:
      - avenirs-api-network
networks: 
  avenirs-api-network:
    external: true
    name: ${AVENIRS_NETWORK}