ARG JAVA_ALPINE_VERSION=25-jdk-alpine

FROM eclipse-temurin:${JAVA_ALPINE_VERSION} as build
ARG OVERLAY_DIR
ENV AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR=$OVERLAY_DIR
ARG MAVEN_VERSION=3.9.9
COPY ./maven-dist/apache-maven-${MAVEN_VERSION}-bin.zip /tmp/maven.zip
RUN unzip -q /tmp/maven.zip -d /opt && ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/local/bin/mvn && rm /tmp/maven.zip
WORKDIR /workspace/app
RUN echo "AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR $AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR"
COPY ./avenirs-portfolio-security/.mvn .mvn
COPY ./avenirs-portfolio-security/pom.xml .
COPY ./avenirs-portfolio-security/libs libs
COPY ./avenirs-portfolio-security/src src
COPY avenirs-portfolio-overlay/avenirs-portfolio-security/src/main/resources/env.properties src/main/resources/

RUN --mount=type=cache,id=maven-repo,target=/root/.m2,sharing=locked mvn clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:${JAVA_ALPINE_VERSION}
WORKDIR /workspace/app
ARG AVENIRS_PORTFOLIO_SECURITY_VERSION=0.0.1
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY avenirs-portfolio-overlay/avenirs-portfolio-security/opt/java/openjdk/lib/security/cacerts /opt/java/openjdk/lib/security/cacerts
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-security-*-SNAPSHOT.jar /app/avenirs-portfolio-security.jar

ARG JAVA_XMX=2048M
ENV JAVA_XMX=${JAVA_XMX}

ENTRYPOINT exec java -server -noverify -Xmx${JAVA_XMX} -jar /app/avenirs-portfolio-security.jar