ARG JAVA_ALPINE_VERSION=21-jdk-alpine

FROM eclipse-temurin:${JAVA_ALPINE_VERSION} as build
WORKDIR /workspace/app
COPY ./avenirs-portfolio-interoperability/mvnw .
COPY ./avenirs-portfolio-interoperability/.mvn .mvn
COPY ./avenirs-portfolio-interoperability/pom.xml .
COPY ./avenirs-portfolio-interoperability/libs libs
COPY ./avenirs-portfolio-interoperability/src src

RUN chmod +x ./mvnw
RUN ./mvnw spotless:apply
RUN ./mvnw clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:${JAVA_ALPINE_VERSION}
WORKDIR /workspace/app
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-interoperability-*-SNAPSHOT.jar /app/avenirs-portfolio-interoperability.jar

ARG JAVA_XMX=2048M
ENV JAVA_XMX=${JAVA_XMX}

ENTRYPOINT exec java -server -noverify -Xmx${JAVA_XMX} -jar /app/avenirs-portfolio-interoperability.jar