FROM eclipse-temurin:21-jdk-alpine as build
WORKDIR /workspace/app
COPY ./avenirs-portfolio-api/mvnw .
COPY ./avenirs-portfolio-api/.mvn .mvn
COPY ./avenirs-portfolio-api/pom.xml .
COPY ./avenirs-portfolio-api/src src

RUN ./mvnw clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:21-jdk-alpine
WORKDIR /workspace/app
ARG AVENIRS_PORTFOLIO_API_VERSION=0.0.1
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-api-${AVENIRS_PORTFOLIO_API_VERSION}-SNAPSHOT.jar /app/avenirs-portfolio-api.jar

ENTRYPOINT ["java", "-server", "-noverify", "-Xmx2048M", "-jar", "/app/avenirs-portfolio-api.jar"]