FROM eclipse-temurin:21-jdk-alpine as build
ARG OVERLAY_DIR
ENV AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR=$OVERLAY_DIR
WORKDIR /workspace/app
RUN echo "AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR $AVENIRS_PORTFOLIO_SECURITY_OVERLAY_DIR"
COPY ./avenirs-portfolio-security/mvnw .
COPY ./avenirs-portfolio-security/.mvn .mvn
COPY ./avenirs-portfolio-security/pom.xml .
COPY ./avenirs-portfolio-security/src src
COPY avenirs-portfolio-overlay/avenirs-portfolio-security/src/main/resources/env.properties src/main/resources/

RUN ./mvnw clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:21-jdk-alpine
WORKDIR /workspace/app
ARG AVENIRS_PORTFOLIO_SECURITY_VERSION=0.0.1
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY avenirs-portfolio-overlay/avenirs-portfolio-security/opt/java/openjdk/lib/security/cacerts /opt/java/openjdk/lib/security/cacerts
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-security-${AVENIRS_PORTFOLIO_SECURITY_VERSION}-SNAPSHOT.jar /app/avenirs-portfolio-security.jar

ENTRYPOINT ["java", "-server", "-noverify", "-Xmx2048M", "-jar", "/app/avenirs-portfolio-security.jar"]