ARG JAVA_ALPINE_VERSION=21-jdk-alpin

FROM eclipse-temurin:${JAVA_ALPINE_VERSION} as build
WORKDIR /workspace/app
COPY ./avenirs-portfolio-back-office/mvnw .
COPY ./avenirs-portfolio-back-office/.mvn .mvn
COPY ./avenirs-portfolio-back-office/pom.xml .
COPY ./avenirs-portfolio-back-office/libs libs
COPY ./avenirs-portfolio-back-office/src src

RUN chmod +x ./mvnw
RUN ./mvnw spotless:apply
RUN ./mvnw clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:${JAVA_ALPINE_VERSION}
WORKDIR /workspace/app
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-back-office-*-SNAPSHOT.jar /app/avenirs-portfolio-back-office.jar

ENTRYPOINT ["java", "-server", "-noverify", "-Xmx2048M", "-jar", "/app/avenirs-portfolio-back-office.jar"]