services:

  avenirs-portfolio-api:
    container_name: ${AVENIRS_PORTFOLIO_API_CONTAINER_NAME}

    build:
      context: .
      dockerfile: ./Dockerfile-avenirs-portfolio-api
      args:
       AVENIRS_PORTFOLIO_API_VERSION: ${AVENIRS_PORTFOLIO_API_VERSION}
       OVERLAY_DIR: ${AVENIRS_PORTFOLIO_API_OVERLAY_BASENAME}
    restart: always
    ports:
      - "${AVENIRS_PORTFOLIO_API_CONTAINER_PORT}:10000"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    depends_on:
      - postgresql-primary
    networks:
      - avenirs-api-network
    volumes:
      - srv-dev_file-storage:/workspace/app/target/storage

  avenirs-portfolio-security:
    container_name: ${AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME}
   
    build:
      context: .
      dockerfile: ./Dockerfile-avenirs-portfolio-security
      args:
       AVENIRS_PORTFOLIO_SECURITY_VERSION: ${AVENIRS_PORTFOLIO_SECURITY_VERSION}
       OVERLAY_DIR: ${AVENIRS_PORTFOLIO_SECURITY_OVERLAY_BASENAME}
    restart: always
    ports:
      - "${AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT}:12000"
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    depends_on:
      - postgresql-primary
    networks:
      - avenirs-api-network

  avenirs-cofolio-client:
    container_name: ${AVENIRS_COFOLIO_CLIENT_CONTAINER_NAME}
   
    build:
      context: ./avenirs-cofolio-client
      dockerfile: ../Dockerfile-avenirs-cofolio-client
      args:
       OVERLAY_DIR: ${AVENIRS_COFOLIO_CLIENT_OVERLAY_BASENAME}
    restart: always
    ports:
      - "${AVENIRS_COFOLIO_CLIENT_CONTAINER_PORT}:80"
    depends_on:
      - avenirs-portfolio-api
    networks:
      - avenirs-api-network

  avenirs-prometheus:
    image: prom/prometheus:latest
    container_name: ${AVENIRS_PROMETHEUS_CONTAINER_NAME}
    restart: always
    ports:
      - "${AVENIRS_PROMETHEUS_CONTAINER_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - avenirs-api-network

  avenirs-grafana:
    image: grafana/grafana:latest
    container_name: ${AVENIRS_GRAFANA_CONTAINER_NAME}
    restart: always
    ports:
      - "${AVENIRS_GRAFANA_CONTAINER_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - avenirs-prometheus
    networks:
      - avenirs-api-network

networks: 
  avenirs-api-network:
    external: true
    name: ${AVENIRS_NETWORK}

volumes:
  srv-dev_file-storage:
    external: true