ARG JAVA_ALPINE_VERSION=21-jdk-alpine

FROM eclipse-temurin:${JAVA_ALPINE_VERSION} as build
WORKDIR /workspace/app
COPY ./avenirs-portfolio-api/mvnw .
COPY ./avenirs-portfolio-api/.mvn .mvn
COPY ./avenirs-portfolio-api/pom.xml .
COPY ./avenirs-portfolio-api/libs libs
COPY ./avenirs-portfolio-api/src src

RUN chmod +x ./mvnw
RUN ./mvnw spotless:apply
RUN ./mvnw clean install package -DskipTests
RUN mkdir -p ./target/dependency && (cd ./target/dependency; jar -xf ../*.jar)


FROM eclipse-temurin:${JAVA_ALPINE_VERSION}
WORKDIR /workspace/app
ARG AVENIRS_PORTFOLIO_API_VERSION=0.0.1
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build /workspace/app/target/avenirs-portfolio-api-*-SNAPSHOT.jar /app/avenirs-portfolio-api.jar

ARG JAVA_XMX=2048M
ENV JAVA_XMX=${JAVA_XMX}

ENTRYPOINT exec java -server -noverify -Xmx${JAVA_XMX} -jar /app/avenirs-portfolio-api.jar