version: '3'
services:
  avenirs-storage-portfolio:
    container_name: ${AVENIRS_PORTFOLIO_STORAGE_CONTAINER_NAME}
    depends_on:
      - postgresql-primary 
      - postgresql-secondary1 
      - postgresql-secondary2
   # image: lets-encrypt-apache:latest
    build:
      context: .
      dockerfile: ./Dockerfile-avenirs-portfolio-storage
      args:
       AVENIRS_PORTFOLIO_STORAGE_VERSION: ${AVENIRS_PORTFOLIO_STORAGE_VERSION}
       OVERLAY_DIR: ${AVENIRS_PORTFOLIO_STORAGE_OVERLAY_BASENAME}
    ports:
      - "${AVENIRS_PORTFOLIO_STORAGE_CONTAINER_PORT}:11000"
    
    networks:
      - avenirs-api-network
networks: 
  avenirs-api-network:
    external: true
    name: ${AVENIRS_NETWORK}