services:
  debezium:
    image: debezium/connect:2.2
    container_name: ${AVENIRS_DEBEZIUM_CONTAINER_NAME}
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium-connect-configs
      OFFSET_STORAGE_TOPIC: debezium-connect-offsets
      STATUS_STORAGE_TOPIC: debezium-connect-status
      PLUGIN_PATH: /kafka/connect
      CONNECTOR_CLASS: io.debezium.connector.postgresql.PostgresConnector
      DATABASE_HOSTNAME: ${AVENIRS_POSTGRESQL_SECONDARY_CDC_CONTAINER_NAME}
      DATABASE_PORT: 5432
      DATABASE_USER: debezium
      DATABASE_PASSWORD: p@@ss4DBZCDC
      DATABASE_DBNAME: realtime_db
      DATABASE_SERVER_NAME: avenirs_realtime
      PLUGIN_NAME: pgoutput
      SLOT_NAME: debezium_slot
      PUBLICATION_NAME: realtime_pub
      PUBLICATION_AUTOCREATE_MODE: disabled
    depends_on:
      - kafka
      - postgresql-secondary-cdc
    networks:
      - debezium-network

  

  register-connector:
    image: curlimages/curl
    container_name: register-connector
    depends_on:
      - debezium
    networks:
      - debezium-network
    entrypoint: >
      sh -c "
      echo 'Waiting for Kafka Connect...';
      
      while ! curl -s http://${AVENIRS_DEBEZIUM_CONTAINER_NAME}:8083/ | grep -q 'kafka'; do
        sleep 5;
      done;
      curl -X POST -H 'Content-Type: application/json' -d '{
        \"name\": \"postgres-connector\",
        \"config\": {
          \"connector.class\": \"io.debezium.connector.postgresql.PostgresConnector\",
          \"database.hostname\": \"${AVENIRS_POSTGRESQL_SECONDARY_CDC_CONTAINER_NAME}\",
          \"database.port\": \"5432\",
          \"database.user\": \"debezium\",
          \"database.password\": \"p@@ss4DBZCDC\",
          \"database.dbname\": \"realtime_db\",
          \"database.server.name\": \"avenirs_realtime\",
          \"plugin.name\": \"pgoutput\",
          \"publication.name\": \"realtime_pub\",
          \"slot.name\": \"debezium_slot\",
          \"topic.prefix\": \"avenirs_rt\",
          \"key.converter\": \"org.apache.kafka.connect.json.JsonConverter\",
          \"value.converter\": \"org.apache.kafka.connect.json.JsonConverter\",
          \"key.converter.schemas.enable\": \"false\",
          \"value.converter.schemas.enable\": \"false\",
          \"tombstones.on.delete\": \"false\"
        }
      }' http://${AVENIRS_DEBEZIUM_CONTAINER_NAME}:8083/connectors"

networks: 
  debezium-network:
    external: true
    name: $AVENIRS_NETWORK
