#! /bin/bash

#--------------------------------------#
# Postgresql bootstrap                 #
#                                      #  
# - Docker .env file to set            #
#   environment from settings.         #
#--------------------------------------#

POSTGRESQL_SCRIPT_DIR=`dirname $0`


# Initialization
. $POSTGRESQL_SCRIPT_DIR/../../../scripts/srv-dev-commons.sh
init_help "`basename $0`"
init_commons $*
info "POSTGRESQL bootstrapping started."
. $POSTGRESQL_SCRIPT_DIR/POSTGRESQL-env.sh $POSTGRESQL_SCRIPT_DIR || err "Unable to source $PWD/$POSTGRESQL_SCRIPT_DIR/POSTGRESQL-env.sh"

# Network check
check_network

# .env file generation
echo "AVENIRS_POSTGRESQL_CONTAINER_NAME=$AVENIRS_POSTGRESQL_CONTAINER_NAME" > $POSTGRESQL_ENV_FILE
echo "POSTGRESQL_OVERLAY_DIR=$POSTGRESQL_OVERLAY_DIR" >> $POSTGRESQL_ENV_FILE
echo "POSTGRESQL_OVERLAY_BASENAME=$POSTGRESQL_OVERLAY_BASENAME" >> $POSTGRESQL_ENV_FILE
echo "AVENIRS_NETWORK=$AVENIRS_NETWORK" >> $POSTGRESQL_ENV_FILE

# Proxy settings
cat $POSTGRESQL_PROXY_SETTINGS_TEMPLATE_FILE | \
    sed s/AVENIRS_POSTGRESQL_CONTAINER_NAME/${AVENIRS_POSTGRESQL_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_OPENLDAP_CONTAINER_NAME__/${AVENIRS_OPENLDAP_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_LDAP_ADMIN_CONTAINER_NAME__/${AVENIRS_LDAP_ADMIN_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME__/${AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_API_CONTAINER_NAME__/${AVENIRS_APISIX_API_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_ETCD_CONTAINER_NAME__/${AVENIRS_APISIX_ETCD_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME__/${AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_GRAFANA_CONTAINER_NAME__/${AVENIRS_APISIX_GRAFANA_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_KAFKA_UI_CONTAINER_NAME__/${AVENIRS_KAFKA_UI_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_CAS_CONTAINER_NAME__/${AVENIRS_CAS_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_NODE_CONTAINER_NAME__/${AVENIRS_NODE_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_NODE_CONTAINER_PORT__/${AVENIRS_NODE_CONTAINER_PORT}/g | \
    sed s/__AVENIRS_API_CONTAINER_NAME__/${AVENIRS_API_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_API_CONTAINER_PORT__/${AVENIRS_API_CONTAINER_PORT}/g > \
    $POSTGRESQL_PROXY_SETTINGS_FILE


# POSTGRESQL envvars generation
echo "export AVENIRS_POSTGRESQL_CONTAINER_NAME=$AVENIRS_POSTGRESQL_CONTAINER_NAME" > $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_OPENLDAP_CONTAINER_NAME=$AVENIRS_OPENLDAP_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_LDAP_ADMIN_CONTAINER_NAME=$AVENIRS_LDAP_ADMIN_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME=$AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_APISIX_API_CONTAINER_NAME=$AVENIRS_APISIX_API_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_APISIX_ETCD_CONTAINER_NAME=$AVENIRS_APISIX_ETCD_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME=$AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_APISIX_GRAFANA_CONTAINER_NAME=$AVENIRS_APISIX_GRAFANA_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE
echo "export AVENIRS_CAS_CONTAINER_NAME=$AVENIRS_CAS_CONTAINER_NAME" >> $POSTGRESQL_ENVVARS_FILE


info "POSTGRESQL bootstrapping completed."