services:
  le-apache:
    container_name: '${AVENIRS_APACHE_CONTAINER_NAME}'
   # image: lets-encrypt-apache:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./httpd.conf:/etc/apache2/httpd.conf
    #   - ./html:/var/www/localhost/htdocs/
    networks:
      - avenirs-network
networks: 
  avenirs-network:
    external: true