#! /bin/bash

#--------------------------------------#
# Apache bootstrap                     #
#                                      #  
# - Docker volumes                     #
# - Docker .env file to set            #
#   environment from settings.         #
#--------------------------------------#

APACHE_SCRIPT_DIR=`dirname $0`


# Initialization
. $APACHE_SCRIPT_DIR/../../../scripts/srv-dev-commons.sh
init_help "`basename $0`"
init_commons $*
info "Apache bootstrapping started."
. $APACHE_SCRIPT_DIR/apache-env.sh $APACHE_SCRIPT_DIR || err "Unable to source $PWD/$APACHE_SCRIPT_DIR/apache-env.sh"

# Network check
check_network

# .env file generation
echo "AVENIRS_APACHE_CONTAINER_NAME=$AVENIRS_APACHE_CONTAINER_NAME" > $APACHE_ENV_FILE
echo "APACHE_OVERLAY_DIR=$APACHE_OVERLAY_DIR" >> $APACHE_ENV_FILE
echo "APACHE_OVERLAY_BASENAME=$APACHE_OVERLAY_BASENAME" >> $APACHE_ENV_FILE
echo "AVENIRS_NETWORK=$AVENIRS_NETWORK" >> $APACHE_ENV_FILE

# Proxy settings
cat $APACHE_PROXY_SETTINGS_TEMPLATE_FILE | \
    sed s/AVENIRS_APACHE_CONTAINER_NAME/${AVENIRS_APACHE_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_OPENLDAP_CONTAINER_NAME__/${AVENIRS_OPENLDAP_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_LDAP_ADMIN_CONTAINER_NAME__/${AVENIRS_LDAP_ADMIN_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME__/${AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_API_CONTAINER_NAME__/${AVENIRS_APISIX_API_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_ETCD_CONTAINER_NAME__/${AVENIRS_APISIX_ETCD_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME__/${AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_APISIX_GRAFANA_CONTAINER_NAME__/${AVENIRS_APISIX_GRAFANA_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_POSTGRESQL_UI_CONTAINER_NAME__/${AVENIRS_POSTGRESQL_UI_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_KAFKA_UI_CONTAINER_NAME__/${AVENIRS_KAFKA_UI_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_CAS_CONTAINER_NAME__/${AVENIRS_CAS_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_NODE_CONTAINER_NAME__/${AVENIRS_NODE_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_NODE_CONTAINER_PORT__/${AVENIRS_NODE_CONTAINER_PORT}/g | \
    sed s/__AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME__/${AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT__/${AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT}/g | \
    sed s/__AVENIRS_API_CONTAINER_NAME__/${AVENIRS_API_CONTAINER_NAME}/g | \
    sed s/__AVENIRS_API_CONTAINER_PORT__/${AVENIRS_API_CONTAINER_PORT}/g > \
    $APACHE_PROXY_SETTINGS_FILE


# Apache envvars generation
echo "export AVENIRS_APACHE_CONTAINER_NAME=$AVENIRS_APACHE_CONTAINER_NAME" > $APACHE_ENVVARS_FILE
echo "export AVENIRS_OPENLDAP_CONTAINER_NAME=$AVENIRS_OPENLDAP_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_LDAP_ADMIN_CONTAINER_NAME=$AVENIRS_LDAP_ADMIN_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME=$AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_APISIX_API_CONTAINER_NAME=$AVENIRS_APISIX_API_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_APISIX_ETCD_CONTAINER_NAME=$AVENIRS_APISIX_ETCD_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME=$AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_APISIX_GRAFANA_CONTAINER_NAME=$AVENIRS_APISIX_GRAFANA_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE
echo "export AVENIRS_CAS_CONTAINER_NAME=$AVENIRS_CAS_CONTAINER_NAME" >> $APACHE_ENVVARS_FILE


info "Apache bootstrapping completed."