services:
  avenirs-api:
    container_name: ${AVENIRS_API_CONTAINER_NAME}
   # image: lets-encrypt-apache:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
       AVENIRS_API_VERSION: ${AVENIRS_API_VERSION}
       OVERLAY_DIR: ${AVENIRS_OVERLAY_BASENAME}
    ports:
      - "${AVENIRS_API_CONTAINER_PORT}:10000"
    
    networks:
      - avenirs-api-network
networks: 
  avenirs-api-network:
    external: true
    name: ${AVENIRS_NETWORK}