services:
  cas:
    container_name: ${AVENIRS_CAS_CONTAINER_NAME}
    depends_on:
      - openldap
    build: .
    ports:
     - "8443:8443"
     - "8081:8080"
    networks:
      - cas-network
networks: 
  cas-network:
    external: true
    name: ${AVENIRS_NETWORK}