# #! /bin/bash
set -eo pipefail
#--------------------------------------#
# Bootstrap script for the dev env     #
#                                      #
# Executes the bootstrap script for    #
# each service                         #
#--------------------------------------#

SRV_DEV_SCRIPT_DIR=$(dirname $0)
OVERWRITE=false

FILTERED_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --overwrite|-overwrite)
      OVERWRITE=true
      ;;
    *)
      FILTERED_ARGS+=("$arg")
      ;;
  esac
done
export OVERWRITE
set -- "${FILTERED_ARGS[@]}"

# Initialization
. $SRV_DEV_SCRIPT_DIR/srv-dev-commons.sh
init_help "$(basename $0)" "[-s|--services service [-s|--service service (...)]"
init_commons "$@"
. $SRV_DEV_SCRIPT_DIR/srv-dev-env.sh $SRV_DEV_SCRIPT_DIR 2> /dev/null || err "Unable to source $SRV_DEV_SCRIPT_DIR/srv-dev-env.sh"
init_services


# .env file generation function
function generate_env_file() {
    local target_file=$1
    info "Generating .env file at $target_file"

    echo "# Generated by bootstrap script on $(date)" > "$target_file"
    echo "AVENIRS_NETWORK=$AVENIRS_NETWORK" >> "$target_file"
    # The MinIO service carries the "minio" profile, so it is only started when the
    # portfolio API is configured to use it rather than an online S3 service or the
    # plain filesystem.
    if [ "$AVENIRS_PORTFOLIO_STORAGE_BACKEND" = "minio" ]; then
        echo "COMPOSE_PROFILES=minio" >> "$target_file"
    else
        echo "COMPOSE_PROFILES=" >> "$target_file"
    fi
    echo "" >> "$target_file"

    function write_section() {
        local section_name=$1
        shift
        local techs=("$@")

        echo "# --- $section_name ---" >> "$target_file"
        
        for tech in "${techs[@]}"; do
            if [ "$tech" == "CAS_BASE_IMAGE" ]; then
                local env_var_name="BASE_IMAGE"
                local default_var_name="CAS_BASE_IMAGE_DEFAULT"
            else
                local env_var_name="${tech}_VERSION"
                local default_var_name="${tech}_VERSION_DEFAULT"
            fi

            local value="${!default_var_name}"
            echo "$env_var_name=${value:-latest}" >> "$target_file"
        done
        echo "" >> "$target_file"
    }
    
    # 1. Infrastructure & Web
    local infra_web=(
        "ALPINE"
        "DEBIAN"
        "HTTPD"
        "NGINX"
    )
    write_section "Infrastructure & Web" "${infra_web[@]}"

    # 2. Databases & Stores
    local databases=(
        "ADMINER"
        "ETCD"
        "POSTGRES"
        "REDIS"
        "VALKEY"
        "MINIO"
        "MINIO_MC"
    )
    write_section "Databases & Stores" "${databases[@]}"

    # 3. Identity & Security
    local identity=(
        "CAS_BASE_IMAGE"
        "OPENLDAP"
        "PHPLDAPADMIN"
    )
    write_section "Identity & Security" "${identity[@]}"

    # 4. Messaging & Search
    local messaging=(
        "KAFKA"
        "KAFKA_UI"
        "OPENSEARCH"
        "OPENSEARCH_DASHBOARDS"
        "ZOOKEEPER"
    )
    write_section "Messaging & Search" "${messaging[@]}"

    # 5. Apisix & Gateway
    local apisix=(
        "APISIX"
        "APISIX_DASHBOARD"
        "OPENRESTY"
    )
    write_section "Apisix & Gateway" "${apisix[@]}"

    # 6. Monitoring
    local monitoring=(
        "GRAFANA"
        "PROMETHEUS"
    )
    write_section "Monitoring" "${monitoring[@]}"

    # 7. Java / Temurin
    local java=(
        "JAVA"
        "JAVA_ALPINE"
    )
    write_section "Java / Temurin" "${java[@]}"

    # 8. Node.js Variations
    local node=(
        "NODE"
        "NODE_ALPINE"
        "NODE_BUILDER"
    )
    write_section "Node.js Variations" "${node[@]}"

    # 9. Languages & Utils
    local utils=(
        "GOLANG"
    )
    write_section "Languages & Utils" "${utils[@]}"

    echo "# --- System ---" >> "$target_file"
    echo "DOCKER_GROUP=$DOCKER_GROUP" >> "$target_file"

    verbose ".env file generated successfully."
}

# Execute generation
generate_env_file "$SRV_DEV_ENV_FILE"


# Bootstrap a service
function bootstrap_service() {
    local service=$1
    info "Bootstrapping  service $service"
    local script=$SERVICES_ROOT/$service/scripts/$service-bootstrap.sh
    vvverbose "Target script: $script"
    [ -e "$script" ] || err "script not found: $script"
    [ -x "$script" ] || err "script not executable: $script"
    info "running: $script"
    $script
}

# Bootstrap all services
function bootstrap_services() {
    info "Boostrapping started."
    vvverbose "Current directory $PWD"
    for service in $SERVICES
    do
        bootstrap_service $service
        # TODO: check exit statut(JASYPT)
    done
    info "---"
    info "Bootstrapped services: $SERVICES"
    info "Completed"
}

check_docker_group() {
    [ -n "$DOCKER_GROUP" ] || err "DOCKER_GROUP is missing in srv-dev-env.sh"
    verbose "Using docker group: $DOCKER_GROUP"
    local entry=""
    OS=$(detect_os)

    if [ $OS = "Mac" ]; then
        entry=$(dscl . -list /Groups | grep -e "^$DOCKER_GROUP$")
    else
        entry=$(grep -e "^$DOCKER_GROUP:" /etc/group)
    fi

    if [ -z "$entry" ]; then
        verbose "Group $DOCKER_GROUP not found"
        if [ $OS = "Mac" ]; then
            dscl . -create /Groups/$DOCKER_GROUP
        else
            groupadd $DOCKER_GROUP
        fi
        verbose "Group $DOCKER_GROUP created"
    else
        verbose "Docker group \"$DOCKER_GROUP\" found"
    fi
}

function check_prerequisites(){
    # Checks the docker group
    check_docker_group

    # Checks that the user is member of Docker group
    vvverbose "Checking that user $USER is member of docker group $DOCKER_GROUP"
    groups | grep -qw $DOCKER_GROUP
    [ $? -ne 0 ] && err "User $USER is not member of docker group $DOCKER_GROUP"
    verbose "User $USER is memberof docker group $DOCKER_GROUP"

    # Checks the docker volume roots
    [ -n "$VOLUMES_ROOT" ] || err "VOLUMES_ROOT is missing in srv-dev-env.sh"
    [ -e $VOLUMES_ROOT -a ! -d $VOLUMES_ROOT ] && err "Volumes root $VOLUMES_ROOT exists but is not a directory"

    if [ ! -e $VOLUMES_ROOT ]
    then
        vvverbose "Volumes root not found: $VOLUMES_ROOT, trying to create"
        sudo mkdir -p $VOLUMES_ROOT || err "Unable to create $VOLUMES_ROOT"
        sudo chgrp $DOCKER_GROUP $VOLUMES_ROOT || err "Unable to change owner group of $VOLUMES_ROOT to $DOCKER_GROUP"
        sudo chmod g+u $VOLUMES_ROOT || err "Unable to change permission on $VOLUMES_ROOT (chmod g+u)"
        sudo chmod g+s $VOLUMES_ROOT || err "Unable to change permission on $VOLUMES_ROOT (chmod g+s)"
        info "Volume root $VOLUMES_ROOT created."
    else
        info "Volumes root checked $VOLUMES_ROOT"
    fi
}

check_prerequisites
check_network
bootstrap_services
