#! /bin/bash

#--------------------------------------#
# Settings for the srv-dev scripts     #
#--------------------------------------#
SRV_DEV_SCRIPT_DIR=$1
SERVICES_ROOT="$SRV_DEV_SCRIPT_DIR/../services"
DOCKER_GROUP="docker"



# Docker env file
SRV_DEV_ENV_FILE=$SRV_DEV_SCRIPT_DIR/../.env

# ---- Docker environment variables that can be overridden
# global
VOLUMES_ROOT=/var/lib/docker-containers/dev.avenirs-esr.fr
AVENIRS_NETWORK=avenirs-network
AVENIRS_CONTAINER_PREFIX=avenirs-
AVENIRS_OPENLDAP_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}openldap"
AVENIRS_LDAP_ADMIN_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}phpldapadmin"
AVENIRS_APACHE_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}apache"
AVENIRS_APISIX_CONTAINER_PREFIX="${AVENIRS_CONTAINER_PREFIX}apisix-"
AVENIRS_APISIX_DASHBOARD_CONTAINER_NAME="${AVENIRS_APISIX_CONTAINER_PREFIX}dashboard"
AVENIRS_APISIX_API_CONTAINER_NAME="${AVENIRS_APISIX_CONTAINER_PREFIX}api"
AVENIRS_APISIX_ETCD_CONTAINER_NAME="${AVENIRS_APISIX_CONTAINER_PREFIX}etcd"
AVENIRS_APISIX_PROMETHEUS_CONTAINER_NAME="${AVENIRS_APISIX_CONTAINER_PREFIX}prometheus"
AVENIRS_APISIX_GRAFANA_CONTAINER_NAME="${AVENIRS_APISIX_CONTAINER_PREFIX}grafana"
AVENIRS_APISIX_INIT_CONTAINER_NAME="${AVENIRS_APISIX_CONTAINER_PREFIX}init"
AVENIRS_POSTGRESQL_UI_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}pgsql-ui"
AVENIRS_CAS_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}cas"
AVENIRS_KAFKA_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}kafka"
AVENIRS_KAFKA_UI_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}kafka-ui"
AVENIRS_ZOOKEEPER_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}zookeeper"
AVENIRS_NODE_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}node"
AVENIRS_NODE_CONTAINER_PORT=8030
AVENIRS_WS_CONTAINER_PORT=8033
AVENIRS_PORTFOLIO_CONTAINER_PREFIX="avenirs-portfolio-"
AVENIRS_POSTGRESQL_PRIMARY_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}pgsql-primary"
AVENIRS_POSTGRESQL_PRIMARY_EXPORTER_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}pgsql-primary-exporter"
AVENIRS_POSTGRESQL_SECONDARY1_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}pgsql-secondary1"
AVENIRS_POSTGRESQL_SECONDARY2_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}pgsql-secondary2"
AVENIRS_PORTFOLIO_API_CONTAINER_NAME="${AVENIRS_PORTFOLIO_CONTAINER_PREFIX}api"
AVENIRS_PORTFOLIO_API_CONTAINER_PORT=10001
AVENIRS_PORTFOLIO_SECURITY_CONTAINER_NAME="${AVENIRS_PORTFOLIO_CONTAINER_PREFIX}security"
AVENIRS_PORTFOLIO_SECURITY_CONTAINER_PORT=10003
AVENIRS_COFOLIO_CLIENT_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}cofolio-client"
AVENIRS_COFOLIO_CLIENT_CONTAINER_PORT=10005
AVENIRS_PROMETHEUS_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}prometheus"
AVENIRS_PROMETHEUS_CONTAINER_PORT=10006
AVENIRS_GRAFANA_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}grafana"
AVENIRS_GRAFANA_CONTAINER_PORT=10007
AVENIRS_OPENSEARCH_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}opensearch"
AVENIRS_OPENSEARCH_CONTAINER_PORT=9200
AVENIRS_OPENSEARCH_DASHBOARDS_CONTAINER_NAME="${AVENIRS_CONTAINER_PREFIX}opensearch-dashboards"
AVENIRS_OPENSEARCH_DASHBOARDS_CONTAINER_PORT=5601
AVENIRS_PORTFOLIO_BACK_OFFICE_CONTAINER_NAME="${AVENIRS_PORTFOLIO_CONTAINER_PREFIX}back-office"
AVENIRS_PORTFOLIO_BACK_OFFICE_CONTAINER_PORT=10008

# ---------------------------------------------------------
# ---- Docker Image Versions (Defaults)
# ---------------------------------------------------------

# Infrastructure & Web
export ALPINE_VERSION_DEFAULT="3.18"
export DEBIAN_VERSION_DEFAULT="bullseye-slim"
export HTTPD_VERSION_DEFAULT="2.4.56"
export NGINX_VERSION_DEFAULT="alpine"

# Databases & Stores
export ADMINER_VERSION_DEFAULT="latest"
export ETCD_VERSION_DEFAULT="3.5"
export POSTGRES_VERSION_DEFAULT="17"
export REDIS_VERSION_DEFAULT="7.0-alpine"
export VALKEY_VERSION_DEFAULT="latest"

# Identity & Security
export CAS_BASE_IMAGE_DEFAULT="eclipse-temurin:11-jdk-alpine"
export OPENLDAP_VERSION_DEFAULT="1.5.0"
export PHPLDAPADMIN_VERSION_DEFAULT="latest"

# Messaging & Search
export KAFKA_VERSION_DEFAULT="latest"
export KAFKA_UI_VERSION_DEFAULT="latest"
export OPENSEARCH_VERSION_DEFAULT="latest"
export OPENSEARCH_DASHBOARDS_VERSION_DEFAULT="latest"
export ZOOKEEPER_VERSION_DEFAULT="latest"

# Apisix & Gateway
export APISIX_VERSION_DEFAULT="3.6.0-debian"
export APISIX_DASHBOARD_VERSION_DEFAULT="3.0.1-alpine"
export OPENRESTY_VERSION_DEFAULT="1.21.4.2-alpine-fat"

# Monitoring
export GRAFANA_VERSION_DEFAULT="latest"
export PROMETHEUS_VERSION_DEFAULT="latest"

# Java / Temurin
export JAVA_ALPINE_VERSION_DEFAULT="21-jdk-alpine"
export JAVA_VERSION_DEFAULT="21-jdk"

# Node.js Variations
export NODE_ALPINE_VERSION_DEFAULT="22-alpine"
export NODE_BUILDER_VERSION_DEFAULT="16-alpine"
export NODE_VERSION_DEFAULT="18"
export GOLANG_VERSION_DEFAULT="1.19"