services:
  node:
    container_name: ${AVENIRS_NODE_CONTAINER_NAME}
    restart: unless-stopped
    #environment:
    #  - APP_RUNNING_CONTEXT=${APP_RUNNING_CONTEXT}

    build:
      context: ./node-api/
      dockerfile: Dockerfile
    #  args:
    #    APP_RUNNING_CONTEXT: ${APP_RUNNING_CONTEXT}
    ports:
      - "${AVENIRS_NODE_CONTAINER_PORT}:3000"
      - "${AVENIRS_WS_CONTAINER_PORT}:3003"

    #volumes:
    #  - /var/log/docker-containers/audit/node:/usr/src/app/logs
   
    networks:
      - node-network
networks: 
  node-network:
    external: true
    name: ${AVENIRS_NETWORK}
