services:
  node:
    container_name: ${AVENIRS_NODE_CONTAINER_NAME}
    restart: always

    build:
      context: ./node-api/
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "${AVENIRS_NODE_CONTAINER_PORT}:3000"
      - "${AVENIRS_WS_CONTAINER_PORT}:3003"
   
    networks:
      - node-network
networks: 
  node-network:
    external: true
    name: ${AVENIRS_NETWORK}
