name: Deploy prerelease server
on:
  release:
    types: [prereleased]

jobs:
  call-deploy-workflow:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/deploy-workflow.yaml@main
    with:
      tag_name: ${{ github.event.release.tag_name }}
    secrets: inherit