name: Deploy prerelease server
on:
  push:

jobs:
  call-deploy-workflow:
    uses: avenirs-esr/avenirs-workflows/.github/workflows/deploy-workflow.yaml@main
    with:
      tag_name: 0.0.1-qa
    secrets: inherit