services:

  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: ${AVENIRS_KAFKA_CONTAINER_NAME}
    restart: always
    ports:
      - 29092:29092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${AVENIRS_KAFKA_CONTAINER_NAME}:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@${AVENIRS_KAFKA_CONTAINER_NAME}:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes: 
      - kafka_data:/var/lib/kafka/data 
    networks:
      kafka-network:

  kafka-ui:
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION}
    container_name: ${AVENIRS_KAFKA_UI_CONTAINER_NAME}
    restart: always
    
    depends_on:
      - kafka
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: avenirs-dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${AVENIRS_KAFKA_CONTAINER_NAME}:9092
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
    networks:
      kafka-network:
networks: 
  kafka-network:
    external: true
    name: $AVENIRS_NETWORK

volumes:
  kafka_data: