# Resources: 
# - https://docs.confluent.io/platform/current/installation/docker/installation.html
# - https://www.baeldung.com/ops/kafka-docker-setup
version: '3'
services:
  zookeeper:
   # user: "3000:999"
    container_name: ${AVENIRS_ZOOKEEPER_CONTAINER_NAME}
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes: 
      - ${AVENIRS_ZOOKEEPER_VOLUMES_ROOT}/data:/var/lib/zookeeper/data
      - ${AVENIRS_ZOOKEEPER_VOLUMES_ROOT}/log:/var/lib/zookeeper/log    
    networks:
      kafka-network:
  
  kafka:
    #user: "3000:999"
    image: confluentinc/cp-kafka:latest
    container_name: ${AVENIRS_KAFKA_CONTAINER_NAME}
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${AVENIRS_ZOOKEEPER_CONTAINER_NAME}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${AVENIRS_KAFKA_CONTAINER_NAME}:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes: 
      - ${AVENIRS_KAFKA_VOLUMES_ROOT}/data:/var/lib/kafka/data 
    networks:
      kafka-network:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${AVENIRS_KAFKA_UI_CONTAINER_NAME}
    
    depends_on:
      - kafka
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: avenirs-dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: avenirs-kafka:9092
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
    networks:
      kafka-network:
    # volumes:
    #   - ${KAFKA_UI_OVERLAY_REALPATH}/etc/kafkaui/dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml
networks: 
  kafka-network:
    external: true
    name: $AVENIRS_NETWORK